### ISSUE TITLE
problems with building

### ISSUE THREAD

**Issue by J2ch** [noradtux/evnotipi-watchdog#3]
I have a problem with the building process. When I want to upload the code to the board, this error message is printed:

![grafik](https://github.com/noradtux/evnotipi-watchdog/assets/152388890/9feec09c-1ebc-4d56-9b49-f68911958766)

**Comment by noradtux** [comment]
Looks like an incompatible change in the "Time" library. I did some adjustment, but can't test right now. Please pull and see if it fixes the build.

**Comment by J2ch** [comment]
Yes, this fixed the problem thanks.
